name: First Workflow
on:workflow_dispatch
jobs: 
  first-job:
    runs-on:
      steps:
        - name: Print a greeting 
            run:echo "Hello World:"
              - name: Print a bye
                run:echo "Good Bye"
        
